erDiagram
    Cubierta }o--|| Navio : tiene
    Camarote }o--|| Cubierta : tiene

    Viaje ||--o{ Itinerarioviaj : para
    Orden }o--|| Itinerario : tiene
    Tipo_itinerario ||--o{ Itinerario : pertenece
    Orden ||--o{ Puerto : posee
    Tripulante ||--o{ ViajeX_Navio : asigna
    ViajeX_Navio }o--|| Viaje : puede_ser
    Navio ||--o{ ViajeX_Navio : puede_ser

    Reserva ||--o{ Pago : paga
    
    Cliente ||--o{ Reserva : hace
    Reserva ||--o{ Pasajero : incluye


    
    MetodoPago ||--o{ Pago : usa
    EstadoPago ||--o{ Pago : clasifica
    EstadoReserva ||--o{ Reserva : clasifica
    Trabajador ||--o{ Tripulante: puede_ser
    Itinerarioviaj }o--|| Itinerario : sigue
    
    ViajeX_Navio ||--o{ Reserva : tiene
    Tipo_de_navio ||--o{ Navio : tiene

    Usuario ||--o{ Cliente : representa


    Estado_Camarote ||--o{ Camarote :Puede
    
    Actividades_posibles ||--o{ Puertoxactividad : Posee
    Puerto ||--o{ Puertoxactividad : Posee

    Lugar_ocupa }o--|| Puerto : tiene
    
    HistorialReserva }o--|| Reserva : registra_cambios
    HistorialPago }o--|| Pago : registra_cambios
    
    Rol ||--o{ Usuario : tiene
    Tripulante ||--o{ OcupacionCamarote : es_tripulante
    Pasajero ||--o{ OcupacionCamarote : es_pasajero
    Camarote ||--o{ OcupacionCamarote : asignado_a

    Pasajero }|--|| EstadoPasajero : tiene

    Camarote }|--|| TipoCamarote : tiene

    
    TipoPersona ||--o{ OcupacionCamarote : define

    TipoPersona {
    int id_tipo_persona PK
    string descripcion
    }

    OcupacionCamarote {
        int id_ocupacion_camarote PK
        int id_camarote FK
        int id_tipo_persona FK
        int id_persona
        date fecha_inicio
        date fecha_fin
    }


    HistorialReserva {
        int id_historial_reserva PK
        int id_reserva FK
        date fecha_cambio
        string cambio_realizado

    }

    HistorialPago {
        int id_historial_pago PK
        int id_pago FK
        date fecha_cambio
        string cambio_realizado
        int estado_pago FK
        int usuario_responsable FK
    }

    Puertoxactividad{
        int id_puertoxactividad PK
        int puerto FK
        int actividades FK
    }

    Estado_Camarote{
        Int id_estado_camarote
        string descripcion
    }
    Pago {
        int id_pago PK
        int reserva FK
        date fecha_pago
        float monto
        int metodo_pago FK
        int estado_pago FK
        date created_at
        date updated_at
    }

    MetodoPago {
        int id_metodo_pago PK
        string nombre
        string descripcion
    }

    EstadoPago {
        int id_estado_pago PK
        string nombre
        string descripcion
    }

    ViajeX_Navio {
        int Id_Viaje_Navio PK
        int Navio FK
        int Viaje FK
        int Tripulante FK
    }

    Tipo_de_navio {
        int id_tipo_tripulante PK
        string nombre
        string descripcion
    }

    Camarote {
        int id_camarote PK
        int numero_de_camarote
        int numero_de_cubierta FK
        int id_estado_camarote FK
        int id_tipo_camarote FK
    }
    TipoCamarote {
        int id_tipo_camarote PK
        string nombre
        string descripcion
    }

    Cubierta {
        int numero_de_cubierta PK
        int navio_perteneciente FK
        string descripcion
        string encargado
    }

    Navio {
        int codigo_de_navio PK
        string nombre
        float altura
        float eslora
        float manga
        float desplazamiento
        int autonomia_de_viaje
        int cantidad_maxima_de_pasajeros
        int cantidad_de_motores
        int Tipo_de_navio FK
    }

    Viaje {
        int id_viaje PK
        string nombre
        string descripcion
        date fecha_de_salida
        date fecha_fin
        time hora_salida
        time hora_llegada
        string lugar_destino
        img imagen
        date fecha_actual
    }

    Trabajador {
        int id_trabajador PK
        string nombre
        int id_usuario FK
    }

    Tripulante {
        int id_Tripulante PK
        string legajo
        int id_trabajador FK
        date fecha_inicio
        date fecha_fin
    }

    Cliente {
        int Id_cliente PK
        string nombre
        int id_usuario FK
        string apellido
        string dni
        string direccion
        date fecha_nacimiento
        string nacionalidad
        string genero

    }

    Pasajero {
        int id_pasajero PK
        int id_reserva FK
        string nombre
        string apellido
        date fecha_inicio
        date fecha_fin
        int id_estado_pasajero FK

    }

    EstadoPasajero {
        int id_estado_pasajero PK
        string nombre
        string descripcion
    }

    Reserva {
        int id_reserva PK
        string descripcion
        int Id_Viaje_Navio FK
        int EstadoReserva FK
        int Cliente FK
        date created_at
        date updated_at
    }

    EstadoReserva {
        int id_estado_reserva PK
        string nombre
        string descripcion
    }

    Itinerario {
        int id_itinerario PK
        int categoria FK
    }

    Orden {
        int id_orden PK
        string nombre
        string descripcion
        int orden
    }

    Puerto {
        int id_puerto PK
        string nombre
        int lugar_ocupa
    }

    Lugar_ocupa {
        int id_lugar_ocupa
        int puerto FK
        int nro_muelle
        string nombre
    }

    Actividades_posibles {
        int id_actividad PK
        string nombre
        string descripciones 
    }

    Tipo_itinerario {
        int id_categoria PK
        string nombre
        string descripcion
    }

    Itinerarioviaj {
        int id_itinerarioviaje PK
        int viaje FK
        int itinerario FK
    }



    Usuario {
        int id_usuario PK
        string username
        string email
        string Contrasenia
        int id_rol FK
        
    }
    Rol {
        int id_rol PK
        string nombre
        string descripcion
    }

