# Generated by Django 4.2.24 on 2025-09-30 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compania_naviera', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
