# Generated by Django 5.2 on 2025-09-15 13:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compania_naviera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camarote',
            name='capacidad',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='camarote',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='puerto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='puerto',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='puerto',
            name='pais',
            field=models.CharField(default='Argentina', max_length=50),
        ),
        migrations.AddField(
            model_name='reserva',
            name='camarote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compania_naviera.camarote'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripulante',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripulante',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripulante',
            name='rol',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='actividadposible',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
