# Generated by Django 5.2.5 on 2025-08-18 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compania_naviera', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='metodo_pago',
        ),
    ]
