# Generated by Django 5.2.7 on 2025-10-02 13:35

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compania_naviera', '0002_remove_usuariopersonalizado_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puerto',
            name='itinerario',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nacionalidad',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='puerto',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puertos', to='compania_naviera.orden'),
        ),
        migrations.AlterField(
            model_name='tripulante',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1),
        ),
        migrations.AlterField(
            model_name='tripulante',
            name='nacionalidad',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='lugar_destino',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
