# Generated by Django 5.2 on 2025-09-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compania_naviera', '0002_camarote_capacidad_camarote_precio_base_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo_iso', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
    ]
