# Generated by Django 5.2 on 2025-08-25 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compania_naviera', '0003_itinerario_puerto_crucero_itinerario_puerto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerario',
            name='puerto',
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('puerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='compania_naviera.puerto')),
            ],
        ),
        migrations.DeleteModel(
            name='Crucero',
        ),
        migrations.DeleteModel(
            name='Itinerario',
        ),
    ]
