# Generated by Django 5.2 on 2025-09-15 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compania_naviera', '0003_pais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pais',
            name='codigo_iso',
        ),
        migrations.AlterField(
            model_name='puerto',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='puertos', to='compania_naviera.pais'),
        ),
    ]
