# Generated by Django 4.2.24 on 2025-10-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compania_naviera', '0004_usuariopersonalizado_pais_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='telefono',
        ),
        migrations.AddField(
            model_name='camarote',
            name='capacidad',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
