# Generated by Django 5.2.6 on 2025-09-19 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compania_naviera', '0002_remove_usuariopersonalizado_metodo_pago_and_more'),
        ('compania_naviera', '0004_remove_pais_codigo_iso_alter_puerto_pais'),
    ]

    operations = [
    ]
