# Generated by Django 4.2.24 on 2025-10-20 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compania_naviera', '0005_remove_usuariopersonalizado_pais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocupacioncamarote',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocupaciones', to='compania_naviera.reserva'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='camarote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='compania_naviera.camarote'),
        ),
    ]
