# Generated by Django 5.2.6 on 2025-09-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('compania_naviera', '0005_merge_20250919_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='usuario_personalizado_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='usuario_personalizado_permissions_set', to='auth.permission'),
        ),
    ]
