# Generated by Django 4.2.24 on 2025-10-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compania_naviera', '0006_ocupacioncamarote_reserva_reserva_camarote'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasajero',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pasajero',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
