# Generated by Django 4.2.24 on 2025-10-26 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compania_naviera', '0007_pasajero_dni_pasajero_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialpago',
            name='estado_pago',
        ),
        migrations.RemoveField(
            model_name='historialpago',
            name='pago',
        ),
        migrations.RemoveField(
            model_name='historialpago',
            name='usuario_responsable',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='estado_pago',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='reserva',
        ),
        migrations.DeleteModel(
            name='EstadoPago',
        ),
        migrations.DeleteModel(
            name='HistorialPago',
        ),
        migrations.DeleteModel(
            name='MetodoPago',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
