# Generated by Django 4.2.24 on 2025-11-06 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compania_naviera', '0008_remove_historialpago_estado_pago_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orden',
            options={'ordering': ['orden']},
        ),
        migrations.AlterField(
            model_name='itinerarioviaje',
            name='itinerario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='compania_naviera.itinerario'),
        ),
        migrations.AlterField(
            model_name='itinerarioviaje',
            name='viaje',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='itinerario_viaje', to='compania_naviera.viaje'),
        ),
    ]
