# Generated by Django 4.2.24 on 2025-11-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compania_naviera', '0009_alter_orden_options_alter_itinerarioviaje_itinerario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
    ]
